In [3]:
import pandas as pd
import numpy as np
import random

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

Las dimensiones, las series son unidimensionales y los DataFrame bidimensionales.


2.Momento de trabajar con Series. Contesta a las siguientes preguntas:

    Crea dos listas:

        Una que se llame "valores" que tenga 7 números aleatorios.

        Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

    A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

    A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

    Crea una Serie con el diccionario creado en el punto anterior.

    ¿Qué forma tiene esta última Serie?

    ¿Qué tipo de datos tiene?

    ¿Qué tamaño tiene?

    ¿Cuáles son los índices de la Serie?

    ¿Y los values?

    Extrae el valor para el índice "lunes"

    Extrae el valor para el índice "lunes", "martes" y "miércoles".

    Extrae el valor para el índice "lunes" y "domingo".

In [9]:
# Crea dos listas

valores = list(random.sample(range(1,20),7))

print(f'nuestra lista de valores aleatorios es :{valores}')


indices = ['lunes','martes','miercoles', 'jueves', 'viernes','sabado','domingo']

print(f'nuestra lista de indices es: {indices}')

nuestra lista de valores aleatorios es :[14, 18, 15, 7, 6, 2, 13]
nuestra lista de indices es: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']


In [14]:
#Crea una serie

weekly_serie = pd.Series(valores,index = indices)

print(f'la serie creada es :\n{weekly_serie}')

la serie creada es :
lunes        14
martes       18
miercoles    15
jueves        7
viernes       6
sabado        2
domingo      13
dtype: int64


In [19]:
#Crea un diccionario

dict_weekly = {}

for indice, valor in zip(indices, valores):
    dict_weekly[indice]=valor

print(f'nuestro diccionario es:{dict_weekly}')

nuestro diccionario es:{'lunes': 14, 'martes': 18, 'miercoles': 15, 'jueves': 7, 'viernes': 6, 'sabado': 2, 'domingo': 13}


In [21]:
#Crea una serie a partir de un diccionario

weekly_serie_dict = pd.Series(dict_weekly)

print(weekly_serie_dict)

lunes        14
martes       18
miercoles    15
jueves        7
viernes       6
sabado        2
domingo      13
dtype: int64


In [24]:
#Forma de la serie

print(f'la forma de la serie es: {weekly_serie_dict.shape}')

la forma de la serie es: (7,)


In [25]:
#Tipo de dato

print(f'el tipo de la serie es {weekly_serie_dict.dtype}')

el tipo de la serie es int64


In [26]:
#Tamaño

print(f'el tamaño de la serie es: {weekly_serie_dict.size}')

el tamaño de la serie es: 7


In [28]:
#indices

print(f'los indices de la serie son:\n{weekly_serie_dict.index}')

los intices de la serie son:
Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')


In [29]:
#valores

print(f'los valore de la serie son:\n{weekly_serie_dict.values}')

los valore de la serie son:
[14 18 15  7  6  2 13]


In [34]:
#valor indice lunes

print(f'el valor del indice para el lunes es: {weekly_serie_dict["lunes"]}')

el valor del indice para el lunes es: 14


In [37]:
#valor indice lunes, martes y miércoles

print(f'el valor del indice para el lunes, martes y miercoles son:\n{weekly_serie_dict["lunes":"miercoles"]}')

el valor del indice para el lunes, martes y miercoles son:
lunes        14
martes       18
miercoles    15
dtype: int64


In [42]:
#valor indice Lunes y domingo

print(f'el valor del indice para el lunes y domingo son:\n{weekly_serie_dict[["lunes" , "domingo"]]}')

el valor del indice para el lunes y domingo son:
lunes      14
domingo    13
dtype: int64


3. Es el turno de los DataFrames:

    Crea un array de dos dimensiones con 4 filas y 3 columnas.

    Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

    Descarga el archivo "medallas" y carga el DataFrame.

    Usando el loc extrae todas las columnas de la fila de Tailandia.

    Usando el loc extrae todas las columnas de China e Irán.

    Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

    Usando el iloc extrae la información de la India. Devolved todas las columnas.

    Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

    Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

    Contesta a las siguientes preguntas:

    ¿Qué país consiguió más de 200 medallas de oro?

    ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

    ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

    Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [91]:
#Array de dos dimensiones con 4 filas y 3 columnas

array1 = np.random.randint(1,101,(4,3))

print(f'El array es\n{array1}')

El array es
[[68 48 11]
 [ 9 52 42]
 [88 54 60]
 [52 86 45]]


In [92]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_array1 = pd.DataFrame(array1,columns=("España","Francia","Italia"))

print(f'el data frame es :\n{df_array1}')

el data frame es :
   España  Francia  Italia
0      68       48      11
1       9       52      42
2      88       54      60
3      52       86      45


In [93]:
#Descarga el archivo "medallas" y carga el DataFrame.

medallas = pd.read_csv('medallas.csv',index_col=0)

print(f'el Dataframe medallas es:\n{medallas}')

el Dataframe medallas es:
               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235


In [97]:
#Extraer todas las columnas de la fila Tailandia utilizando LOC

print(f'El total de medallas para Tailandia son\n{medallas.loc[7,:]}')

El total de medallas para Tailandia son
País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object


In [100]:
#Extraer todas las columnas de la fila China e Iran utilizando LOC

print(f'El total de medallas para China e Iran son:\n{medallas.loc[1:4:3,:]}')

El total de medallas para China e Iran son:
    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197


In [103]:
#Extraer columnas Oro, plata y bronce de los paises China e Iran utilizando LOC

print(f'El total de medallas para China e Iran sin mostrar el país son:\n {medallas.loc[1:4:3, "Oro":"Bronce"]}')

El total de medallas para China e Iran sin mostrar el país son:
     Oro  Plata  Bronce
1  1473    994     720
4   179    181     197


In [106]:
# Extraer infomracion de la India utilizando ILOC

print(f'El total de medallas de India son:\n{medallas.iloc[5,:]}')

El total de medallas de India son:
País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object


In [108]:
# Extraer todas las filas de la posicion impar utilizando ILOC

medallas_impar = medallas.iloc[1::2,]

print(f'Las medallas en posicions impares son\n {medallas_impar}')

Las medallas en posicions impares son
                País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235


In [109]:
# Seleccionar oro, plata y bronce de las filas impar utilizando ILOC

print(f'Las medallas en posiciones impares sin incluir el país son:\n{medallas_impar.iloc[:,1:]}')

Las medallas en posiciones impares sin incluir el país son:
     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235


In [112]:
# ¿Que país consiguió mas de 200 medallas de oro?

print(f'Los países que consiguieron mas medallas de oro son:\n{medallas.loc[medallas["Oro"]>200,"País"]}')

Los países que consiguieron mas medallas son:
1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object


In [117]:
#¿Que país consiguó mas de 200 medallas de oro y más de 1000 de plata?

print(f'Los países que consiguieron mas de 200 de oro y más de 1000 de plata es:\n{medallas.loc[(medallas["Oro"]>200) & (medallas["Plata"]>1000),"País"]}')

Los países que consiguieron mas de 200 de oro y más de 1000 de plata es:
2    Japón
Name: País, dtype: object


In [118]:
#¿Que país consiguó mas de 200 medallas de oro o más de 700 de bronce?

print(f'Los países que consiguieron mas de 200 de oro y más de 700 de bronce es:\n{medallas.loc[(medallas["Oro"]>200) | (medallas["Bronce"]>700),"País"]}')

Los países que consiguieron mas de 200 de oro y más de 700 de bronce es:
1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object
