In [3]:
import numpy as np

## Creación e Indexación

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [4]:
array1D = np.random.randint(10 , 100, (50))
print(f"El array es:\n{array1D}")

El array es:
[51 85 74 83 11 57 72 79 36 62 35 84 35 62 60 43 29 23 51 16 83 83 62 62
 10 36 82 49 39 82 26 42 71 26 83 21 38 33 91 73 28 91 44 65 73 62 73 98
 37 52]


In [5]:
print(f"Los elementos en posiciones múltiplos de 5 son: {array1D[4::5]}")

Los elementos en posiciones múltiplos de 5 son: [11 62 60 16 10 82 83 73 73 52]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [6]:
array1D_2 = np.random.randint(1 , 21, (30))
print(f"El array es:\n{array1D_2}")

El array es:
[19 19 20 10  5  6 17  1 11 15  5 20  4  8  4  5 12  1  1  1 18 13  7  9
 17  1 19  6 19 13]


In [7]:
print(f"Los elementos en posiciones impares son: {array1D_2[1::2]}")

Los elementos en posiciones impares son: [19 10  6  1 15 20  8  5  1  1 13  9  1  6 13]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [8]:
array_2d = np.random.uniform(10, 100, (4, 6)) # Hemos utilizado random.uniform para poder obtener datos aleatorios de tipo float, pero dándole un rango distinto a 0 y 1, ya que randint devuelve integers
print(f"El array es:\n{array_2d}")

El array es:
[[52.15580706 21.77405803 40.974721   41.53899375 13.08178245 85.4996518 ]
 [81.42356589 68.50658497 12.39167899 31.14068668 83.75500357 40.75982187]
 [32.14434555 74.18880476 58.30659797 21.81494527 50.14922568 28.37413802]
 [52.87930607 49.60295473 40.36508538 34.30133907 90.83519857 54.20426261]]


In [9]:
print(f"Los elementos de la última fila son: {array_2d[-1]}")

Los elementos de la última fila son: [52.87930607 49.60295473 40.36508538 34.30133907 90.83519857 54.20426261]


In [10]:
array_2d_redondeado = np.round(array_2d, 2)
print(f"El array redondeado es:\n{array_2d_redondeado}")

El array redondeado es:
[[52.16 21.77 40.97 41.54 13.08 85.5 ]
 [81.42 68.51 12.39 31.14 83.76 40.76]
 [32.14 74.19 58.31 21.81 50.15 28.37]
 [52.88 49.6  40.37 34.3  90.84 54.2 ]]


4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [11]:
array_2d_2 = np.random.sample((6, 4))
print(f"El array es:\n{array_2d_2}")

El array es:
[[0.87162445 0.98126814 0.27386212 0.67778242]
 [0.84252166 0.791782   0.89024233 0.60740523]
 [0.21846222 0.08834839 0.36344673 0.49067906]
 [0.08082639 0.53169325 0.64424639 0.61026058]
 [0.46567572 0.75909578 0.30437118 0.14315461]
 [0.41847595 0.16463744 0.01327053 0.71462741]]


In [12]:
print(f"Los elementos de la segunda columna son:\n {array_2d_2[: , 1]}")

Los elementos de la segunda columna son:
 [0.98126814 0.791782   0.08834839 0.53169325 0.75909578 0.16463744]


In [13]:
array_2d_redondeado_2 = np.round(array_2d_2, 2)
print(f"El array redondeado es:\n{array_2d_redondeado_2}")

El array redondeado es:
[[0.87 0.98 0.27 0.68]
 [0.84 0.79 0.89 0.61]
 [0.22 0.09 0.36 0.49]
 [0.08 0.53 0.64 0.61]
 [0.47 0.76 0.3  0.14]
 [0.42 0.16 0.01 0.71]]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [14]:
array1D_3 = np.random.randint(-50 , 50 , (30))
print(f"El array es:\n{array1D_3}")

El array es:
[ 28  -2 -47 -30 -39 -10  39 -23  28  41 -42  -9 -45   8  -8  30 -41 -45
  28 -19  47 -21  15  16  31 -37 -16  37  49 -24]


In [15]:
numeros_negativos = array1D_3 < 0

print(f"Los números negativos son:\n{array1D_3[numeros_negativos]}")

Los números negativos son:
[ -2 -47 -30 -39 -10 -23 -42  -9 -45  -8 -41 -45 -19 -21 -37 -16 -24]


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [16]:
array1D_4 = np.random.sample(10)
print(f"El array es:\n{array1D_4}")

El array es:
[0.17710658 0.41116725 0.98289997 0.83864759 0.97481143 0.88974956
 0.15241685 0.0536863  0.15455018 0.4476847 ]


In [17]:
array1D_4_redondeado = np.round(array1D_4, 2)
print(f"El array redondeado es:\n{array1D_4_redondeado}")

El array redondeado es:
[0.18 0.41 0.98 0.84 0.97 0.89 0.15 0.05 0.15 0.45]


In [18]:
mayores = array1D_4_redondeado > 0.5

print(f"Los números mayores a 0.5 son:\n{array1D_4_redondeado[mayores]}")

Los números mayores a 0.5 son:
[0.98 0.84 0.97 0.89]


In [19]:
print(f"Los números están en la posición:\n{np.where(array1D_4_redondeado[mayores])}")

Los números están en la posición:
(array([0, 1, 2, 3]),)


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [20]:
array1D_5 = np.arange(1 , 101 , 100/40 , dtype=int)
print(f"El array es:\n{array1D_5}")

El array es:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79]


In [21]:
divisibles = (array1D_5 % 3 == 0) & (array1D_5 % 4 == 0)

print(f"Los elementos divisibles por 3 y por 4 son:\n {array1D_5[divisibles]}")

Los elementos divisibles por 3 y por 4 son:
 []


BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [22]:
array3D = np.random.randint(0 , 101 , (2 , 3, 5)) # Si quisiéramos 50 elementos tendríamos que ajustar la forma del array que se está generando, ya que con 2x3x5 obtenemos 30
array3D_50 = np.random.randint(0 , 101 , (2 , 5, 5))
print(f"El array con 30 elementos es:\n{array3D}")
print(f"\nEl array con 50 elementos es:\n{array3D_50}")

El array con 30 elementos es:
[[[ 0  9 68 24 20]
  [61 45 67 28 26]
  [45 81 53 27 48]]

 [[66 42 78 65  8]
  [15 82 43 83  9]
  [40 66 69 97 62]]]

El array con 50 elementos es:
[[[55 51 85 18 92]
  [78 96 21 29 21]
  [88  4 66 69 92]
  [51 25 41 20 26]
  [78 62 47 52 28]]

 [[93 16 89  4 84]
  [68 18 25 39 66]
  [68 46 87 40 58]
  [32 11 80 98 57]
  [80 11 57 44 37]]]


In [23]:
array3D_50_ceros = np.where(array3D_50 % 3 == 0 , 0 , array3D_50)

print(f"El array cambiando sus elementos es:\n{array3D_50_ceros}")

El array cambiando sus elementos es:
[[[55  0 85  0 92]
  [ 0  0  0 29  0]
  [88  4  0  0 92]
  [ 0 25 41 20 26]
  [ 0 62 47 52 28]]

 [[ 0 16 89  4  0]
  [68  0 25  0  0]
  [68 46  0 40 58]
  [32 11 80 98  0]
  [80 11  0 44 37]]]


## Reshape y Transpose

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [24]:
array3D_2 = np.random.randint(0 , 101 , (2 , 3, 4))
print(f"El array 3D es:\n{array3D_2}")

El array 3D es:
[[[19 33 32 78]
  [81 54  7 33]
  [14 42 82 38]]

 [[42 73 26 54]
  [64  8 32 87]
  [ 5 45 41 60]]]


In [25]:
array3D_convertido = np.reshape(array3D_2 , (6,4))
print(f"El array 2D es:\n{array3D_convertido}")

El array 2D es:
[[19 33 32 78]
 [81 54  7 33]
 [14 42 82 38]
 [42 73 26 54]
 [64  8 32 87]
 [ 5 45 41 60]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [26]:
array3D_3 = np.random.randint(1 , 60 , (3, 4, 5))
print(f"El array 3D es:\n{array3D_3}")

El array 3D es:
[[[25  1 24 32 23]
  [ 3  8 11 48 42]
  [ 9 58 30  4 21]
  [28 13 18  1 17]]

 [[ 1 20 43 31  4]
  [55 30 19 58 28]
  [17 37 18 44 57]
  [45 58 28 34  4]]

 [[12 40 45 16  2]
  [47 18  9 42  9]
  [ 4 50  6  1 27]
  [27 38 27  8  3]]]


In [27]:
array3D_3_convertido = np.reshape(array3D_3 , (6,10))
print(f"El array 2D es:\n{array3D_3_convertido}")

El array 2D es:
[[25  1 24 32 23  3  8 11 48 42]
 [ 9 58 30  4 21 28 13 18  1 17]
 [ 1 20 43 31  4 55 30 19 58 28]
 [17 37 18 44 57 45 58 28 34  4]
 [12 40 45 16  2 47 18  9 42  9]
 [ 4 50  6  1 27 27 38 27  8  3]]


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [28]:
array3D_4 = np.random.sample((4, 3, 2))
print(f"El array 3D es:\n{array3D_4}")

El array 3D es:
[[[0.99695287 0.77202339]
  [0.76560897 0.70946527]
  [0.94978416 0.17875388]]

 [[0.17910665 0.8793873 ]
  [0.75790226 0.28783756]
  [0.38262927 0.04672082]]

 [[0.22362904 0.10507665]
  [0.73983841 0.56649699]
  [0.7174719  0.95446696]]

 [[0.46434144 0.86779902]
  [0.4622805  0.53836558]
  [0.22177587 0.17855802]]]


In [29]:
array3D_4_convertido = np.reshape(array3D_4 , (4,6))
print(f"El array 2D es:\n{array3D_4_convertido}")

El array 2D es:
[[0.99695287 0.77202339 0.76560897 0.70946527 0.94978416 0.17875388]
 [0.17910665 0.8793873  0.75790226 0.28783756 0.38262927 0.04672082]
 [0.22362904 0.10507665 0.73983841 0.56649699 0.7174719  0.95446696]
 [0.46434144 0.86779902 0.4622805  0.53836558 0.22177587 0.17855802]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [30]:
array3D_3_transp = np.transpose(array3D_3 , (2, 1, 0)) # Le decimos que ahora en nuestra posición 0 (matriz) queremos lo que el array tenía en su posición 2 (columnas), que en la posición 1 (filas) mantenemos su posición 1 (filas) y que en la posición 2 (columnas) queremos el número que tenía en la posición 0 (matriz)
print(f"El array 3D transposeado es:\n{array3D_3_transp}")

El array 3D transposeado es:
[[[25  1 12]
  [ 3 55 47]
  [ 9 17  4]
  [28 45 27]]

 [[ 1 20 40]
  [ 8 30 18]
  [58 37 50]
  [13 58 38]]

 [[24 43 45]
  [11 19  9]
  [30 18  6]
  [18 28 27]]

 [[32 31 16]
  [48 58 42]
  [ 4 44  1]
  [ 1 34  8]]

 [[23  4  2]
  [42 28  9]
  [21 57 27]
  [17  4  3]]]


5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [31]:
array3D_4_transp = np.transpose(array3D_4 , (1 , 2 , 0))
print(f"El array 3D transposeado es:\n{array3D_4_transp}")

El array 3D transposeado es:
[[[0.99695287 0.17910665 0.22362904 0.46434144]
  [0.77202339 0.8793873  0.10507665 0.86779902]]

 [[0.76560897 0.75790226 0.73983841 0.4622805 ]
  [0.70946527 0.28783756 0.56649699 0.53836558]]

 [[0.94978416 0.38262927 0.7174719  0.22177587]
  [0.17875388 0.04672082 0.95446696 0.17855802]]]


6. ¿Qué diferencia existe entre el reshape y el transpose?

Respuesta: En el reshape cambias directamente la forma del array (indicas su forma nueva) y en el transpose cambias los índices para que se adecúen a la nueva forma

7. ¿Y entre el transpose y el swapaxes?

Respuesta: La diferencia es que el primero permite reordenar todos los ejes (índices) en una nueva forma y con swapaxes podemos intercambiar dos ejes de esa array para darle esa nueva forma

## Funciones Aritméticas y Estadísticas

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [35]:
array3D_5 = np.random.sample((2 , 3, 5))
array3D_5 = np.round(array3D_5 , 1)
print(f"El array es:\n{array3D_5}")

El array es:
[[[0.6 0.4 0.1 0.1 0. ]
  [0.7 0.3 0.7 0.  0.3]
  [0.7 0.8 0.3 0.8 0.2]]

 [[0.3 0.8 0.9 0.  0.7]
  [0.3 0.5 0.6 0.2 0.3]
  [0.8 0.2 0.4 0.9 0. ]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [51]:
array3D_6 = np.empty((2 , 3, 5))
array3D_6 = np.round(array3D_6 , 1)
print(f"El array es:\n{array3D_6}")

El array es:
[[[0.6 0.4 0.1 0.1 0. ]
  [0.7 0.3 0.7 0.  0.3]
  [0.7 0.8 0.3 0.8 0.2]]

 [[0.3 0.8 0.9 0.  0.7]
  [0.3 0.5 0.6 0.2 0.3]
  [0.8 0.2 0.4 0.9 0. ]]]


In [54]:
media = np.round(np.mean(array3D_6) , 1)
maximo = np.max(array3D_6)
minimo = np.min(array3D_6)

array_letras = np.where(array3D_6 == maximo , "D" , np.where(array3D_6 == minimo , "E" , np.where(array3D_6 == media , "A" , np.where(array3D_6 < media , "C" , "B"))))
print(f"El array convertido es:\n{array_letras}")

El array convertido es:
[[['B' 'A' 'C' 'C' 'E']
  ['B' 'C' 'B' 'E' 'C']
  ['B' 'B' 'C' 'B' 'C']]

 [['C' 'B' 'D' 'E' 'B']
  ['C' 'B' 'B' 'C' 'C']
  ['B' 'C' 'A' 'D' 'E']]]


In [57]:
# Definimos las condiciones y los valores a asignar para cada una
condiciones = [array3D_6 < media, array3D_6 > media , array3D_6 == maximo, array3D_6 == minimo , array3D_6 == media]
valores = ["C" , "B" , "D", "E" , "A"]

# Asignamos valores utilizando np.where()
for condicion, valor in zip(condiciones, valores):
    array_letras_2 = np.where(condicion, valor, array_letras)

print(f"El array convertido es:\n{array_letras_2}")

El array convertido es:
[[['B' 'A' 'C' 'C' 'E']
  ['B' 'C' 'B' 'E' 'C']
  ['B' 'B' 'C' 'B' 'C']]

 [['C' 'B' 'D' 'E' 'B']
  ['C' 'B' 'B' 'C' 'C']
  ['B' 'C' 'A' 'D' 'E']]]
